site_name: ترجمه سایت javascript.info

theme:
  name: 'material'
  language: 'fa'
  direction: 'rtl'
  theme:
  palette:
    primary: green
    accent: 'red'
  font: true
  feature:
    tabs: true
extra_css:
  - 'stylesheets/extra.css'

nav:
- صفحه اصلی : 'index.md'
- مقدمات  :
  - مقدمه‌ای بر جاوا اسکریپت: 'part-one-introduction/0-An_Introduction_to_JavaScript.md'
  - معرفی منابع مفید: 'part-one-introduction/1-Manuals_Specifications.md'
  - ویرایشگر کد: 'part-one-introduction/2-Code_Editors.md'
  - کنسول مرورگر : 'part-one-introduction/3-Developer_Console.md'
- پایه جاوا اسکریپت :
  - سلام دنیا! : 'part-two-javascript-fundamentals/hello_world.md'
  - ساختار کد: 'part-two-javascript-fundamentals/structure.md'
  - حالت سخت‌ گیرانه : 'part-two-javascript-fundamentals/use_strict.md'
  - متغیر ها : 'part-two-javascript-fundamentals/variables.md'
